feat: also update deploy repository in bootstrap if already existing

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -4,7 +4,7 @@ set -uo pipefail
 
 umask 077
 function die() { echo "[1;31merror:[m $*" >&2; exit 1; }
-function status() { echo "[1m$*[m"; }
+function status() { echo "[1;33m$*[m"; }
 TTY="/dev/$(ps -p $$ -o tty=)"
 
 ################################################################
@@ -61,7 +61,11 @@ chown minecraft: /var/lib/minecraft
 cd ~minecraft \
 	|| die "Could not change into ~minecraft"
 
-if [[ ! -e deploy ]]; then
+if [[ -e deploy ]]; then
+	status "Updating deploy repository"
+	runuser -u minecraft git -C deploy pull \
+		|| die "Could not pull repository"
+else
 	status "Cloning deploy repository"
 	runuser -u minecraft git clone "https://github.com/oddlama/minecraft-server" deploy \
 		|| die "Could not clone repository"
@@ -73,7 +77,6 @@ cd deploy \
 echo "eula=true" > server/eula.txt
 chown minecraft: server/eula.txt
 
-status "Updating server and plugins"
 runuser -u minecraft ./update.sh \
 	|| die "Could not update server files"
 
