fix: don't flush stdin, but the TTY

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -10,7 +10,7 @@ TTY="/dev/$(ps -p $$ -o tty=)"
 
 function die() { echo "[1;31merror:[m $*" >&2; exit 1; }
 function status() { echo "[1;33m$*[m"; }
-function flush_stdin() { while read -r -t 0.01 empty_stdin; do true; done; }
+function flush_stdin() { while read -r -t 0.01 empty_stdin < "$TTY"; do true; done; }
 function ask() {
 	local response
 	while true; do
@@ -52,10 +52,8 @@ done
 status "Agree to Mojang EULA"
 echo "You have to agree to Mojang's EULA to use the server software."
 echo "It is available here: https://account.mojang.com/documents/minecraft_eula"
-if ! ask "Do you agree to the EULA?"; then
-	# Cannot use short || syntax, would terminate script when piped into bash due to return (??)
-	die "Installation aborted. EULA must be accepted to continue."
-fi
+ask "Do you agree to the EULA?" \
+	|| die "Installation aborted. EULA must be accepted to continue."
 
 
 ################################################################
