fix: rogue ;; spotted

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -53,7 +53,7 @@ status "Agree to Mojang EULA"
 echo "You have to agree to Mojang's EULA to use the server software."
 echo "It is available here: https://account.mojang.com/documents/minecraft_eula"
 ask "Do you agree to the EULA?" \
-	|| die "Installation aborted. EULA must be accepted to continue." ;;
+	|| die "Installation aborted. EULA must be accepted to continue."
 
 
 ################################################################
