feat: detec RAM and issue warning if too low

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -47,6 +47,23 @@ done
 
 
 ################################################################
+# Ensure memory requirements are met and we have root access
+
+total_ram_gibi=$(free -g | grep -oP '\d+' | head -n1)
+if [[ $total_ram_gibi -le 4 ]]; then
+	echo "[31mYour system has [33m${total_ram_gibi}GiB[31m of RAM, which probably is not enough to run"
+	echo "minecraft without issues. The recommended minimum amount is _at least_ [33m12GiB[31m.[m"
+	ask "Continue anyway?" || die "Installation aborted."
+elif [[ $total_ram_gibi -lt 12 ]]; then
+	echo "[31mYour system has [33m${total_ram_gibi}GiB[31m of RAM, which less than the recommended amount"
+	echo "of _at least_ [33m12GiB[31m. This will hurt the server performance significantly.[m"
+	ask "Continue anyway?" || die "Installation aborted."
+fi
+
+[[ $EUID == 0 ]] || die "Must be root for system-wide installation."
+
+
+################################################################
 # Ensure EULA is accepted
 
 status "Agree to Mojang EULA"
@@ -54,12 +71,6 @@ echo "You have to agree to Mojang's EULA to use the server software."
 echo "It is available here: https://account.mojang.com/documents/minecraft_eula"
 ask "Do you agree to the EULA?" \
 	|| die "Installation aborted. EULA must be accepted to continue."
-
-
-################################################################
-# Ensure root access
-
-[[ $EUID == 0 ]] || die "Must be root for system-wide installation."
 
 
 ################################################################
