docs: improve final message

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -9,7 +9,7 @@ TTY="/dev/$(ps -p $$ -o tty=)"
 # Helper functions
 
 function die() { echo "[1;31merror:[m $*" >&2; exit 1; }
-function status() { echo "${had_status-\n}[1;33m$*[m"; had_status=1; }
+function status() { echo "${had_status+$'\n'}[1;33m$*[m"; had_status=1; }
 function flush_stdin() { while read -r -t 0.01 empty_stdin < "$TTY"; do true; done; }
 function ask() {
 	local response
@@ -78,6 +78,14 @@ chown minecraft: /var/lib/minecraft
 
 ################################################################
 # Setup repository
+
+if [[ -e /var/lib/minecraft/deploy ]]; then
+	echo "[33mThe deploy directory /var/lib/minecraft/deploy already exists."
+	echo "You can still run the installer again, but it may overwrite some"
+	echo "configuration files if you edited them in the meantime.[m"
+	ask "Are you sure you want to continue?" \
+		|| die "Installation aborted."
+fi
 
 cd ~minecraft \
 	|| die "Could not change into ~minecraft"
@@ -149,7 +157,7 @@ if ask "Increase view-distance to 15 chunks?"; then
 		|| die "Could not replace view-distance config"
 fi
 
-
+echo
 runuser -u minecraft -- ./update.sh < "$TTY" \
 	|| die "Could not update server files"
 
@@ -165,34 +173,42 @@ status "Installing service files"
 ################################################################
 # Enable and start services
 
-echo "[33mThe script would now enable and start the system services. If you want to"
-echo "adjust any proxy related configuration, you may want to start them manually"
-echo "at a later point in time.[m"
-if ask "Enable and start system services?"; then
-	status "Starting services ..."
+status "Starting services ..."
+echo "[33mSystem services for the proxy and server will now be enabled and started."
+echo "If you want to adjust any proxy related configuration, you may want to start"
+echo "them manually later.[m"
+echo
+
+postponed_service_message=""
+if ask "Enable and start system services now?"; then
 	systemctl enable --now minecraft-server minecraft-proxy < "$TTY" \
 		|| die "Error while enabling services"
 else
-	echo "[1m===============================================================================[m"
-	echo "[1;33mMake sure to later execute the following command:"
-	echo "[1;32m    systemctl enable --now minecraft-server minecraft-proxy[m"
-	echo "[1m===============================================================================[m"
+	read -d '' postponed_service_message <<EOF
+
+You have postponed enabling the system services. Make sure to execute the
+following command when you are ready to start the server:
+
+[1;32m    systemctl enable --now minecraft-server minecraft-proxy[m
+EOF
 fi
 
 
 ################################################################
-# Appendix
+# Success message
 
 cat <<EOF
-[1m===============================================================================[m
-[1;32mInstallation successful![m
+[1m================================================================================[m
+                            [1;32mInstallation successful![m
+[1m================================================================================[m
 Both the proxy and main server have successfully been enabled! The actual
-minecraft server will be started, when a player connects via the proxy.
+minecraft server will be started when a player connects via the proxy.
 
 Please make sure that TCP port [35m25565[m (server), [35m25566[m (multiplex 1) and [35m8100[m
 (bluemap webserver) are exposed to the internet via a port-foward or similar
 mechanism. If you want to change your server configuration, please do so now.
+$postponed_service_message
 
 For more information, visit [35mhttps://github.com/oddlama/minecraft-server[m
-[1m===============================================================================[m
+[1m================================================================================[m
 EOF
