feat: generate velocity secret

diff --git a/docs/bootstrap b/docs/bootstrap
--- a/docs/bootstrap
+++ b/docs/bootstrap
@@ -35,7 +35,7 @@ function install_file() {
 # Ensure that all required tools are installed
 
 abort=0
-for i in jq git tmux rdiff-backup java; do
+for i in jq git tmux rdiff-backup java openssl; do
 	if ! type "$i" &>/dev/null; then
 		echo "[1;31mmissing: [1;33m$i[m" >&2
 		abort=1
@@ -127,6 +127,12 @@ done
 for f in $(find contrib/default_config -type f -printf '%P\n'); do
 	install_file contrib/default_config/"$f" "$f" minecraft: 600
 done
+
+VELOCITYSECRET=$(openssl rand -base64 16) \
+	|| die "Could not generate velocity secret"
+install_file <(echo -n "$VELOCITYSECRET") proxy/forwarding.secret minecraft: 600
+sed -i 's|{{VELOCITYSECRET}}|'"$VELOCITYSECRET"'|' server/config/paper-global.yml \
+	|| die "Could not insert velocity secret in paper-global.yml"
 
 echo "Depending on your player base, you might want to allow certain gamplay"
 echo "exploits on your server. These are fixed by default in PaperMC, but would"
